apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
      
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'echo "<html><body><h1>Domashnee zadanie 1. Pod podnyat.</h1></body></html>" > /init/index.html']
      volumeMounts:
        - name: shared-volume
          mountPath: /init
          
  containers:
    - name: web-server
      image: python:alpine
      ports:
        - containerPort: 8000
      command: ["sh", "-c", "cd /homework && python -m http.server 8000"]
      volumeMounts:
        - name: shared-volume
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
